### ISSUE TITLE
OmniAuthを用いたgoogle認証機能

### ISSUE THREAD

**Issue by kogoro06** [kogoro06/MySongJournal#120]
### **TODO**
1. **OmniAuthのセットアップ**
   - [ ] `omniauth-google-oauth2` gemをインストール。
   - [ ] Google Cloud ConsoleでOAuthクライアントIDを作成。
   - [ ] クライアントID、クライアントシークレット、リダイレクトURLを設定。
   - [ ] RailsでOmniAuthの初期設定を行う。

2. **Google認証機能の実装**
   - [ ] OmniAuthを用いてGoogleアカウントによる認証を実装。
   - [ ] 認証後、以下のユーザー情報を取得・保存：
     - ユーザー名
     - メールアドレス
     - プロフィール画像（任意）
   - [ ] 初回ログイン時に新しいユーザーを作成。
   - [ ] 認証済みGoogleアカウントでログインできるようにする。

3. **UIの整備**
   - [ ] ログインページに「Googleでログイン」ボタンを追加。
   - [ ] ログイン後、Googleアカウントの名前やメールアドレスを表示。

---

### **要件**
- [ ] Google OAuth 2.0認証が正しく動作し、Googleアカウントを使用したログインが可能である。
- [ ] 初回ログイン時に新規ユーザー登録が自動的に行われる。
- [ ] 認証後に取得したユーザー情報（ユーザー名、メールアドレスなど）が正確にデータベースに保存される。
- [ ] ログイン後、ユーザー情報がアプリ内で正しく表示される。

---
