### ISSUE TITLE
Journalsテーブルに公開状態を管理するカラムを追加

### ISSUE THREAD

**Issue by kogoro06** [kogoro06/MySongJournal#141]
### **TODO**
- [ ] `journals`テーブルに`visibility`カラムを追加。
  - Enumを使用して状態を管理（例: `public`, `private`）。
- [ ] デフォルト値を`public`に設定。

---

### **要件**
- [ ] journalsテーブルに公開状態を管理するカラムが正しく追加されている。
- [ ] Enumによる公開状態の管理が設定されている。
- [ ] 新規作成時のデフォルト値が`public`に設定されている。
