### ISSUE TITLE
RailsアプリケーションでのS3設定

### ISSUE THREAD

**Issue by kogoro06** [kogoro06/MySongJournal#145]
### **TODO**
- [ ] `aws-sdk-s3` Gemをインストール。
- [ ] Railsアプリの`config/storage.yml`にS3用の設定を追加。
- [ ] `Rails.application.credentials`にAWSのキー（`access_key_id`、`secret_access_key`）を保存。
- [ ] 開発環境と本番環境でS3を利用するよう設定。

---

### **要件**
- [ ] RailsアプリケーションでS3を利用するための設定が完了している。
- [ ] 環境ごとに適切なS3バケットが利用される。
