### ISSUE TITLE
共有用URLの生成

### ISSUE THREAD

**Issue by kogoro06** [kogoro06/MySongJournal#172]
### **TODO**
- [ ] 日記タイトル、感情タグ、ページURL、楽曲情報を含むX投稿リンクを生成。
  - 例: `https://twitter.com/intent/tweet?text=日記タイトル&url=ページURL&hashtags=感情タグ`
- [ ] 文字数制限（280文字）を考慮した投稿内容を生成。

#### **要件**
- [ ] Xの投稿画面を開くリンクが正しく生成される。
- [ ] 日記タイトル、感情タグ、楽曲情報が正しく含まれ、文字数制限を満たしている。
